Modify dockerbox console to use nmdm

diff --git a/sbin/dockerbox b/sbin/dockerbox
--- a/sbin/dockerbox
+++ b/sbin/dockerbox
@@ -33,8 +33,11 @@ CONF_DIR=/usr/local/etc/dockerbox
 : "${AWK:=/usr/bin/awk}"
 : "${FETCH:=/usr/bin/fetch}"
 : "${INSTALL:=/usr/bin/install}"
+: "${LS:=/bin/ls}"
+: "${CU:=/usr/bin/cu}"
 
 : "${VMM_KO:=/boot/kernel/vmm.ko}"
+: "${NMDM_KO:=/boot/kernel/nmdm.ko}"
 : "${PF_KO:=/boot/kernel/pf.ko}"
 : "${PF_CONF:=/etc/pf.conf}"
 
@@ -48,6 +51,10 @@ DEVICE_MAP="${GUEST_ROOT}/device.map"
 VM_MANAGER_DAEMON_ID="dockerbox-vm-manager"
 CONFIG="${CONF_DIR}/dockerbox.conf"
 NAT_IP="10.0.0.254"
+
+NMDM_DEVICE=/dev/nmdm-dockerbox
+NMDM_A="${NMDM_DEVICE}.1A"
+NMDM_B="${NMDM_DEVICE}.1B"
 
 help_msg="Usage: sudo dockerbox [command]
 
@@ -63,6 +70,10 @@ log() {
     local _level="$1"
     local _message="$2"
     local _timestamp
+
+    if [ ${_level} == "warn" ] || [ ${_level} == "error" ]; then
+        ${ECHO} "${_message}"
+    fi
 
     _level="$(${ECHO} $_level | tr "[:lower:]" "[:upper:]")"
     _timestamp="$(date +'%FT%H:%M:%S%z')"
@@ -128,14 +139,15 @@ assert_kmod_loaded() {
     log debug "assert loaded: kmod=${_kmod}, kmod_file=${_kmod_file}"
 
     if ! ${KLDSTAT} -q -m "${_kmod}"; then
-        log debug "Kernel module ${_kmod} is not loaded"
+        log warn "Kernel module ${_kmod} is not loaded"
+        log warn "Loading kernel module ${_kmod}"
 
         if ! (${KLDLOAD} "${_kmod_file}" 2>&1 | capture_output debug kldload); then
             log error "${_kmod_file} kernel module could not be loaded"
             exit 127
         fi
 
-        log debug "Kernel module ${_kmod} was loaded successfully"
+        log warn "Kernel module ${_kmod} was loaded successfully"
     fi
 }
 
@@ -265,6 +277,10 @@ check_vmm() {
     assert_kmod_loaded "vmm" "${VMM_KO}"
 }
 
+check_nmdm() {
+    assert_kmod_loaded "nmdm" "${NMDM_KO}"
+}
+
 get_vm_manager_pid() {
     ${PGREP} -fx "daemon: ${VM_MANAGER_DAEMON_ID}\[[0-9]*\]"
 }
@@ -294,12 +310,14 @@ vm_manager() {
     
     cpu=1
     memory=512M
+    console="yes"
 
     log info "Pulling options from configuration file"
     . ${CONFIG}
 
     check_vmm
     check_nat 
+    check_nmdm
 
     if [ ! -f ${DISK_IMAGE} ]; then
 	  	log error "Disk image not installed"
@@ -322,18 +340,14 @@ vm_manager() {
     _grub_args="-m ${DEVICE_MAP} -r hd0,msdos1 -M ${memory}"
     _bhyve_args="-A -H -P -s 0:0,hostbridge -s 1:0,lpc -s 2:0,virtio-net,${_tap} -s 3:0,virtio-blk,${DISK_IMAGE} -s 4:0,virtio-blk,${DOCKER_IMAGE} -c ${cpu} -m ${memory}"
     
-    if [ "$1" == "console" ]; then
-        _bhyve_args="${_bhyve_args} -l com1,stdio"
-        log debug "Grub arguments: ${_grub_args}"
-        ${GRUB_BHYVE} ${_grub_args} ${DOCKERBOX_VM}
-        log debug "Bhyve arguments: ${_bhyve_args}"
-        ${BHYVE} ${_bhyve_args} ${DOCKERBOX_VM} 
-    else
-        log debug "Grub arguments: ${_grub_args}"
-        env TERM=xterm-256color ${GRUB_BHYVE} ${_grub_args} ${DOCKERBOX_VM} 2>&1 | capture_output debug grub-bhyve
-        log debug "Bhyve arguments: ${_bhyve_args}"
-        ${BHYVE} ${_bhyve_args} ${DOCKERBOX_VM} 2>&1 | capture_output debug bhyve
+    if [ "${console}" == "yes" ]; then
+        _bhyve_args="${_bhyve_args} -l com1,${NMDM_A}"
     fi
+
+    log debug "Grub arguments: ${_grub_args}"
+    env TERM=xterm-256color ${GRUB_BHYVE} ${_grub_args} ${DOCKERBOX_VM} 2>&1 | capture_output debug grub-bhyve
+    log debug "Bhyve arguments: ${_bhyve_args}"
+    ${BHYVE} ${_bhyve_args} ${DOCKERBOX_VM} 2>&1 | capture_output debug bhyve
 }
 
 dockerbox_start() {
@@ -357,6 +371,31 @@ dockerbox_start() {
     fi
 }
 
+dockerbox_console() {
+    local _pid
+
+    log info "Begin: dockerbox console"
+    _pid="$(get_vm_manager_pid)"
+    log debug "Dockerbox pid: ${_pid}"
+
+    if [ -z "${_pid}" ]; then
+	    log error "There is no guest to attach to"
+	    exit 127
+    fi
+
+    if ! ${LS} "${NMDM_DEVICE}"* > /dev/null 2>&1; then
+	    log error "No null-modem device is configured"
+	    exit 127
+    fi
+
+    ${ECHO} 'Connecting, type "~." to leave the session...'
+    log info "Attaching to the guest"
+    ${CU} -s 115200 -l ${NMDM_B}
+    log info "Detached from the guest"
+    ${ECHO} "Finished."
+    log info "End: wifibox console"
+}
+
 dockerbox_stop() {
     local _pid
     _pid="$(get_vm_manager_pid)"
@@ -365,8 +404,8 @@ dockerbox_stop() {
     bhyvectl --destroy --vm=${DOCKERBOX_VM}
     destroy_tap
     destroy_bridge
-    ${KILL} -SIGTERM $PPID
-    log info "Dockerbox stopped: killed pid=${_pid} and ppid=${PPID}"
+    #${KILL} -SIGTERM $PPID
+    log info "Dockerbox stopped: killed pid=${_pid}"
 }
 
 dockerbox_status() {
@@ -458,7 +497,7 @@ shift
 case ${command} in
     start) dockerbox_start;;
     stop) dockerbox_stop;;
-    console) dockerbox_start console;;
+    console) dockerbox_console;;
     status) dockerbox_status;;
     fetch) dockerbox_fetch;;
     resize) dockerbox_resize $@;;
